name: Quip Runner

on:
  push
env: 
  repo_dir: Quip-Scripts

jobs:
    entireJob:
        name: Quip Add/Remove User Script
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo 
          uses: actions/checkout@v2
            repository: critical-mass/Quip-Scripts
          
        - name: Running main.py
          run: python ${{ env.repo_dir }}/main.py
          shell: sh
