name: Quip Runner

on:
  push
env: 
  repo_dir: Quip-Scripts

jobs:
    entireJob:
        name: Quip Add/Remove User Script
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo 
          uses: actions/checkout@v2
          with:
            repository: critical-mass/Quip-Scripts
  
        - name: Running main.py
          uses: actions/setup-python@v3
          with: 
            python-version: '3.9'
            check-latest: true
        - run: python main.py
