- name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: critical-mass/Quip-Scripts
          run: python ${{ env.Scripts_dir }}/main.py
