name: Quip-Scripts
on: 
  repository_dispatch:
    types: quip
jobs:
  build:
    name: Quip Scripts
    runs-on: ubuntu-latest
  steps:
   - name: Quip Scrips
    with:
    token: ${{ secrets.REPO_ACCESS_TOKEN }}
      repository: critical-mass/Quip-Scripts
      run: main.py
