name: Run the quip actioin scripts
env: 
  owner: critical-mass
  repo: Quip-Scripts

on:
  repository_dispatch:
    types: [run-Runner]
jobs:
  Runner: 
    runs-on: ubunut-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Quip Scrips
      run: python main.py
